name: py36_torch18
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - ca-certificates=2022.6.15=ha878542_0
  - conda-pack=0.6.0=pyhd3eb1b0_0
  - cycler=0.10.0=py36_0
  - dbus=1.13.18=hb2f20db_0
  - expat=2.4.9=h6a678d5_0
  - fontconfig=2.14.1=hef1e5e3_0
  - freetype=2.12.1=h4a9f257_0
  - glib=2.69.1=h4ff587b_1
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - icu=58.2=he6710b0_3
  - intel-openmp=2022.1.0=h9e868ea_3769
  - jpeg=9b=0
  - kiwisolver=1.3.1=py36h2531618_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.2.0=h85742a9_0
  - libwebp-base=1.2.4=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxml2=2.9.14=h74e7548_0
  - llvm-openmp=8.0.1=hc9558a2_0
  - lz4-c=1.9.4=h6a678d5_0
  - matplotlib=3.3.1=0
  - matplotlib-base=3.3.1=py36h817c723_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py36he8ac12f_0
  - mkl_fft=1.3.0=py36h54f3939_0
  - mkl_random=1.1.1=py36h0573a6f_0
  - natsort=5.1.0=py36_0
  - ncurses=6.4=h6a678d5_0
  - numpy-base=1.19.2=py36hfa32c7d_0
  - olefile=0.44=py36_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=1.1.1l=h7f98852_0
  - pcre=8.45=h295c915_0
  - pip=9.0.1=py36_1
  - pyparsing=2.2.0=py36_0
  - pyqt=5.6.0=py36_2
  - python=3.6.13=h12debd9_1
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.6=2_cp36m
  - qt=5.6.3=h8bf5577_3
  - readline=8.2=h5eee18b_0
  - sip=4.18=py36_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - tornado=4.5.2=py36_0
  - wheel=0.29.0=py36_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.4.9=haebb681_0
  - pip:
    - astunparse==1.6.3
    - botocore==1.26.10
    - cached-property==1.5.2
    - cachetools==4.2.4
    - certifi==2022.6.15
    - charset-normalizer==2.0.12
    - clang==5.0
    - click==8.0.4
    - dataclasses==0.8
    - decorator==4.4.2
    - decord==0.6.0
    - docopt==0.6.2
    - einops==0.4.1
    - filelock==3.4.1
    - flatbuffers==1.12
    - gast==0.4.0
    - google-auth==2.9.1
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - google-protobuf==0.0.1
    - grpcio==1.47.0
    - h5py==3.1.0
    - hjson==3.1.0
    - idna==3.3
    - imageio==2.15.0
    - importlib-resources==5.4.0
    - iopath==0.1.10
    - jmespath==0.10.0
    - joblib==1.1.0
    - jsonpatch==1.32
    - jsonpointer==2.3
    - keras==2.9.0
    - keras-preprocessing==1.1.2
    - networkx==2.5.1
    - ninja==1.10.2.3
    - nltk==3.2.4
    - numpy==1.19.5
    - oauthlib==3.2.0
    - opencv-python==4.6.0.66
    - opt-einsum==3.3.0
    - packaging==21.3
    - pandas==1.1.5
    - pillow==8.4.0
    - pipreqs==0.4.11
    - portalocker==2.6.0
    - preprocessing==0.1.13
    - psutil==5.9.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pytorch-metric-learning==2.3.0
    - pywavelets==1.1.1
    - pyyaml==6.0
    - regex==2022.9.13
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - s3transfer==0.5.2
    - scikit-image==0.17.2
    - scikit-learn==0.24.2
    - scipy==1.5.4
    - seaborn==0.11.2
    - sentencepiece==0.1.97
    - setuptools==59.6.0
    - simplejson==3.18.0
    - six==1.15.0
    - sklearn==0.0
    - sphinx-rtd-theme==0.2.4
    - tensorboard==2.9.1
    - tensorboard-data-server==0.6.1
    - tensorboard-logger==0.1.0
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.5.1
    - tensorflow==2.6.0
    - tensorflow-estimator==2.8.0
    - termcolor==1.1.0
    - threadpoolctl==3.1.0
    - tifffile==2020.9.3
    - timm==0.4.12
    - torch==1.8.1+cu111
    - torchvision==0.9.1+cu111
    - tqdm==4.64.0
    - triton==1.1.1
    - typing-extensions==4.1.1
    - urllib3==1.26.10
    - visdom==0.2.4
    - websocket-client==1.3.1
    - wrapt==1.12.1
    - yacs==0.1.8
    - yarg==0.1.9
    - zipp==3.6.0
prefix: /home/think/anaconda3/envs/py36_torch18
